/* Stress: many POD structs (exceeds the old MAX_UCLASS=32) plus hazard
   structs that must fall back to opaque without corrupting the rest. */
typedef struct { int a; int b; } S1;
typedef struct { int a; int b; } S2;
typedef struct { int a; int b; } S3;
typedef struct { int a; int b; } S4;
typedef struct { int a; int b; } S5;
typedef struct { int a; int b; } S6;
typedef struct { int a; int b; } S7;
typedef struct { int a; int b; } S8;
typedef struct { int a; int b; } S9;
typedef struct { int a; int b; } S10;
typedef struct { int a; int b; } S11;
typedef struct { int a; int b; } S12;
typedef struct { int a; int b; } S13;
typedef struct { int a; int b; } S14;
typedef struct { int a; int b; } S15;
typedef struct { int a; int b; } S16;
typedef struct { int a; int b; } S17;
typedef struct { int a; int b; } S18;
typedef struct { int a; int b; } S19;
typedef struct { int a; int b; } S20;
typedef struct { int a; int b; } S21;
typedef struct { int a; int b; } S22;
typedef struct { int a; int b; } S23;
typedef struct { int a; int b; } S24;
typedef struct { int a; int b; } S25;
typedef struct { int a; int b; } S26;
typedef struct { int a; int b; } S27;
typedef struct { int a; int b; } S28;
typedef struct { int a; int b; } S29;
typedef struct { int a; int b; } S30;
typedef struct { int a; int b; } S31;
typedef struct { int a; int b; } S32;
typedef struct { int a; int b; } S33;
typedef struct { int a; int b; } S34;
typedef struct { int a; int b; } S35;
typedef struct { int a; int b; } S36;
typedef struct { int a; int b; } S37;
typedef struct { int a; int b; } S38;
typedef struct { int a; int b; } S39;
typedef struct { int a; int b; } S40;
typedef struct { int a; int b : 3; int c; } BitF;
typedef struct { int tag; union { int i; char c; } u; } AnonU;
