{ SPDX-License-Identifier: 0BSD }
program devtest_truststore;
{ Hermetic chain-validation devtest for lib/rtl/truststore.pas
  (feature-tls-system-trust-store).

  The certificates are generated by tools/truststore_devtest.sh with the openssl
  CLI — a root, an intermediate it signed, and a leaf the intermediate signed —
  so nothing here touches the network and the only trust anchor is the test root.

  Usage: devtest_truststore <chaindir> <now-YYYYMMDDHHMMSS>

  `now` is passed in rather than read from the clock because the assertions are
  about a fixed validity window; the script derives it from the certificates it
  just made. A `now` before the leaf's notBefore makes every case fail for the
  right reason but the wrong one, which is worth knowing if this ever goes red. }

uses truststore, x509;

var
  failures: Integer;

procedure Check(const name: AnsiString; got, want: Boolean);
begin
  if got = want then
    writeln('ok   ', name)
  else
  begin
    writeln('FAIL ', name, '  got=', got, ' want=', want);
    failures := failures + 1;
  end;
end;

function ReadDer(const path: AnsiString): AnsiString;
var s: AnsiString;
begin
  if not TrustReadFile(path, s) then s := '';
  ReadDer := s;
end;

var
  dir, nowStr: AnsiString;
  store, sysStore, emptyStore: TTrustStore;
  leaf, inter, root, tampered: AnsiString;
  list: array[0..3] of AnsiString;
  i: Integer;

begin
  failures := 0;
  dir := ParamStr(1);
  nowStr := ParamStr(2);
  if (dir = '') or (Length(nowStr) <> 14) then
  begin
    writeln('usage: devtest_truststore <chaindir> <now-YYYYMMDDHHMMSS>');
    Halt(2);
  end;

  leaf  := ReadDer(dir + '/leaf.der');
  inter := ReadDer(dir + '/int.der');
  root  := ReadDer(dir + '/root.der');
  if (leaf = '') or (inter = '') or (root = '') then
  begin
    writeln('FAIL could not read the generated chain from ', dir);
    Halt(1);
  end;

  { --- the PEM decoder, against the chain's own single-cert store --- }
  if not LoadTrustFile(dir + '/store.pem', store) then
  begin
    writeln('FAIL could not load the test store');
    Halt(1);
  end;
  Check('test store holds exactly the one root', store.Count = 1, True);

  { --- accept --- }
  list[0] := leaf; list[1] := inter;
  Check('leaf + intermediate chains to the trusted root',
        VerifyServerChain(store, list, 2, nowStr, 'test.example.com'), True);

  { The TLS spec says the certificate_list is sender-ordered; real servers get
    this wrong often enough that order must not be assumed. }
  list[0] := leaf; list[1] := root; list[2] := inter;
  Check('out-of-order certificate_list still chains',
        VerifyServerChain(store, list, 3, nowStr, 'test.example.com'), True);

  { --- reject --- }
  list[0] := leaf; list[1] := inter;
  Check('hostname mismatch rejected',
        VerifyServerChain(store, list, 2, nowStr, 'evil.example.com'), False);

  Check('missing intermediate rejected (cannot reach the root)',
        VerifyServerChain(store, list, 1, nowStr, 'test.example.com'), False);

  Check('validity window enforced (now before notBefore)',
        VerifyServerChain(store, list, 2, '20200101000000', 'test.example.com'), False);

  { An empty store must trust NOTHING. This is the fail-closed property: the
    loader returning no anchors must never read as "no constraints". }
  emptyStore.Count := 0;
  Check('empty store trusts nothing',
        VerifyServerChain(emptyStore, list, 2, nowStr, 'test.example.com'), False);

  { Flip a byte inside the leaf's signature region. }
  tampered := leaf;
  i := Length(tampered) - 5;
  tampered[i] := Chr((Ord(tampered[i]) xor 255) and 255);
  list[0] := tampered; list[1] := inter;
  Check('tampered leaf signature rejected',
        VerifyServerChain(store, list, 2, nowStr, 'test.example.com'), False);

  { The chain is internally perfect but its root is not an anchor the system
    store knows — the whole point of anchoring. Skipped when the host has no
    system bundle, since then there is nothing to contrast against. }
  list[0] := leaf; list[1] := inter;
  if LoadSystemTrust(sysStore) then
  begin
    writeln('     (system store: ', sysStore.Source, ', ', sysStore.Count, ' roots)');
    Check('internally-valid chain with an untrusted root rejected',
          VerifyServerChain(sysStore, list, 2, nowStr, 'test.example.com'), False);
  end
  else
    writeln('     (no system trust store on this host — untrusted-root case skipped)');

  if failures = 0 then
    writeln('TRUSTSTORE OK')
  else
  begin
    writeln('TRUSTSTORE FAILED (', failures, ')');
    Halt(1);
  end;
end.
