{ write(v:w:d) must not print overflow debris.

  The value used to be scaled by 10^decimals in ONE multiply and rounded into
  an Int64, so `WriteLn(1e16:0:5)` and `WriteLn(267.5:0:17)` both overflowed and
  printed 2^63's own digits with a point pushed in — 92233720368547.75808, a
  plausible-looking number that is entirely debris
  (bug-b-writeln-float-with-17-decimals-prints-garbage).

  Every Chk expectation below is FPC's output for the same program. The integer
  and fractional parts are now scaled separately, and digits past the 18th are
  zeros because a double carries no information there — which is what FPC does
  too (0.1:0:20 agrees on both).

  The WriteLn block at the end is the exception and is checked by the Makefile
  rather than by Chk: its expectations come from decimal.Decimal, the EXACT
  value of the double. FPC is not an oracle for exactness — it computes in
  Extended and prints its own approximation — so it answers what SHOULD be
  printed but never what the digits ARE. }
program lib_writefloat_fixed;

var fails: Integer;

procedure Chk(const what, got, want: AnsiString);
begin
  if got = want then WriteLn(what, '=ok')
  else begin WriteLn(what, ' FAIL got=', got, ' want=', want); fails := fails + 1; end;
end;

var y: Double; s: AnsiString;
begin
  fails := 0;
  y := 2.675 * 100.0;                 { exactly 267.5 }
  Str(y:0:2, s);   Chk('d2',  s, '267.50');
  Str(y:0:15, s);  Chk('d15', s, '267.500000000000000');
  Str(y:0:16, s);  Chk('d16', s, '267.5000000000000000');
  Str(y:0:17, s);  Chk('d17', s, '267.50000000000000000');
  Str(y:0:20, s);  Chk('d20', s, '267.50000000000000000000');
  Str(y:0:30, s);  Chk('d30', s, '267.500000000000000000000000000000');
  Str((-y):0:17, s); Chk('neg', s, '-267.50000000000000000');
  Str(0.1:0:20, s); Chk('tenth20', s, '0.10000000000000000000');
  Str(0.0:0:17, s); Chk('zero', s, '0.00000000000000000');
  { magnitudes where value*10^decimals passes 2^63 — all debris before }
  Str(1e15:0:5, s); Chk('e15', s, '1000000000000000.00000');
  Str(1e16:0:5, s); Chk('e16', s, '10000000000000000.00000');
  Str(1e17:0:5, s); Chk('e17', s, '100000000000000000.00000');
  Str(1e18:0:3, s); Chk('e18', s, '1000000000000000000.000');
  Str(1e-300:0:20, s); Chk('tiny', s, '0.00000000000000000000');
  { rounding still rounds, and a carry out of the fraction lands on the
    integer part }
  Str(0.5:0:0, s);  Chk('half0', s, '1');
  Str(1.5:0:0, s);  Chk('one50', s, '2');
  Str(2.5:0:0, s);  Chk('two50', s, '3');
  Str(0.999:0:2, s); Chk('carry', s, '1.00');
  Str((-0.999):0:2, s); Chk('negcarry', s, '-1.00');
  Str(9.9999:0:3, s); Chk('carry3', s, '10.000');
  { Str goes through StrFloat; WriteLn goes through the CODEGEN writer, which is
    a separate implementation of the same rules — the whole point is that they
    agree, so both are exercised. }
  WriteLn(y:0:2);
  WriteLn(y:0:17);
  WriteLn(y:0:20);
  WriteLn(1e16:0:5);
  WriteLn(0.1:0:20);
  WriteLn(0.5:0:0);
  WriteLn(1.5:0:0);
  WriteLn(2.5:0:0);
  WriteLn(0.999:0:2);
  WriteLn((-y):0:17);
  WriteLn(y:30:5);
  { PAST 2^53 the integer part is expanded EXACTLY, in base-10^9 integer limbs.
    It used to be generated by dividing a double down by powers of ten, and past
    2^53 that recovers the value's BINARY granularity rather than its digits:
    1e25 printed 10000000000000002147483648, whose tail is 2^31 and is no part
    of the number, and 1e300 was wrong from the FIRST significant digit. The
    expectations the Makefile greps for are the exact values of the doubles,
    from `python3 -c "from decimal import Decimal; print(Decimal(float(x)))"` —
    NOT from FPC, which computes in Extended and prints its own approximation,
    so it answers what SHOULD be printed but never what the digits ARE
    (bug-a-write-fixed-emits-false-digits-past-1e22).

    WriteLn only: Str(v:w:d) hands anything past 9.2e18 to FloatToExpStr and
    answers '1e+23', which is the parked
    compat-pascal-write-fixed-huge-magnitude-differs-from-fpc, not this fix. }
  WriteLn(1e23:0:0);
  WriteLn(1e25:0:0);
  WriteLn(1e30:0:2);
  WriteLn((-1e23):0:2);
  WriteLn(1e23:30:0);   { the field width counts the digits actually printed }

  { ...and the FRACTION half of the same number, exact for as many digits as are
    asked for. It used to be scaled through a Double: right for about 16 digits,
    then the product's rounding for two or three more, then ZEROS presented as
    digits — the routine's own comment called that "past what a double knows",
    which was the false premise. A double is mant * 2^exp2 with both parts
    integral, so its decimal expansion is finite and every digit of it is real:
    a denormal runs to 1074 fraction digits and they all mean something.
    Expectations from decimal.Decimal(float(x)) quantized half-away-from-zero.
    bug-a-write-fixed-fraction-digits-past-16-are-invented }
  WriteLn((1/3):0:30);      { ...314829616256247, not ...312 then zeros }
  WriteLn(0.1:0:25);        { ...0055511151, not twenty-four zeros }
  WriteLn(267.5:0:20);      { an exact binary value: really is all zeros }
  WriteLn(9.96:0:1);        { the fraction rounds up INTO the integer }
  WriteLn(0.5:0:0, ' ', 1.5:0:0, ' ', 2.5:0:0);  { half-AWAY-from-zero, not to-even }
  WriteLn((-1/3):0:20);
  if fails = 0 then WriteLn('WRITEFLOAT OK')
  else WriteLn('WRITEFLOAT FAILED ', fails);
end.
