# A str method on a MEMBER reached through a chain -- a property, an attribute
# or a method of a call result -- and a subscript after it, as config and
# header parsing write them: `self.line.split(":")[0]`, `Req().path.strip()`.
# Expected output is CPython's (test/...expected was generated by python3).
#
# Before, NilPy's chained-selector loop (PyParseClassRecordSelectors) got four
# of these wrong, all on pin v443:
#   r.text.split(":")[0]      property   IR_UNSUPPORTED kind 67 (split: the
#                                        str-or-class run-time ternary) or
#                                        kind 8 (partition, rsplit): the loop
#                                        kept a stale class id, so [0] became
#                                        a raw index over a TPyList
#   mk().meth().split(":")[0] method     the same, through the str-method chain
#   R().name.upper()          attribute  TypeError: object is not callable --
#                                        no arm took a method on a str-typed
#                                        member, `upper` became a FIELD
#   mk().meth().upper()[0]    method     '\x00' where CPython prints 'A':
#                                        Pascal's 1-based index, silently
# A named receiver (`r.name.upper()`, `t = r.text; t.split(...)`) was right
# throughout; the chain is what differed.


class R:
    def __init__(self):
        self.name = "ab:cd:ef"

    @property
    def text(self):
        return "ab:cd:ef"

    def meth(self):
        return " ab:cd:ef "


def mk():
    return R()


def mkl():
    return [R()]


def in_a_function():
    r = R()
    print(r.text.split(":")[0], r.text.split(":")[-1], r.text.partition(":")[2])
    print(r.text.rsplit(":", 1)[0], r.text.splitlines()[0], r.text.split(":")[0].upper())
    print(mk().name.upper(), R().name.split(":")[1], len(mk().name.split(":")))
    print(mk().meth().split(":")[0], mk().meth().strip().split(":")[1])
    print(mkl()[0].meth().partition(":")[0], mkl()[0].name.rsplit(":", 1)[1])
    print(mk().meth().upper()[1], mk().name.upper()[-1], R().text.upper()[1:3])
    print("-".join(mk().name.split(":")), mk().name.split(":")[1:])
    print(mk().name.split(":")[0][1], mk().name.find("cd"))


in_a_function()
r = R()
print(r.text.split(":")[0], r.text.partition(":")[0], mk().name.upper()[0])
print(mk().meth().strip().upper()[-1], R().name.split(":")[-1])
