program pasmith_362;
{ GENERATED by tools/pasmith.py -- seed 362. Do not edit.
  Reproduce with: tools/pasmith.py --seed 362
  gen-args: --vars 8 --funcs 3 --stmts 12 --depth 3 --classes 0 --objs 3 --strs 0 --recs 0 --arrs 0 --enums 0 --shorts 0 --excepts 0 --modeprocs 0 --intfs 0 --hier 0 --mptrs 0 --props 0 --exdtor 0 --clsm 0 --checks 0 --consts 0 --wide-p 0.45 }
{$mode objfpc}
{$Q-}
{$R-}

var
  cs: qword;
  g0: shortint;
  g1: byte;
  g2: smallint;
  g3: word;
  g4: longint;
  g5: longword;
  g6: int64;
  g7: qword;
  g8: boolean;
  g9: char;
  g10: boolean;
  g11: boolean;
  g12: char;
  g13: longword;
  g14: word;
  g15: boolean;
  g16: longword;
  g17: char;
  li0: longint;
  li1: longint;
  li2: longint;

procedure Mix(v: int64);
begin
  cs := qword(cs * 1000003) xor qword(v);
end;

procedure MixStr(const s: ansistring);
var i: longint;
begin
  Mix(Length(s));
  for i := 1 to Length(s) do Mix(ord(s[i]));
end;

function SafeDiv_shortint(a, b: shortint): shortint;
begin
  if (b = 0) or (b = -1) then SafeDiv_shortint := a else SafeDiv_shortint := a div b;
end;
function SafeMod_shortint(a, b: shortint): shortint;
begin
  if (b = 0) or (b = -1) then SafeMod_shortint := a else SafeMod_shortint := a mod b;
end;
function SafeDiv_byte(a, b: byte): byte;
begin
  if (b = 0) then SafeDiv_byte := a else SafeDiv_byte := a div b;
end;
function SafeMod_byte(a, b: byte): byte;
begin
  if (b = 0) then SafeMod_byte := a else SafeMod_byte := a mod b;
end;
function SafeDiv_smallint(a, b: smallint): smallint;
begin
  if (b = 0) or (b = -1) then SafeDiv_smallint := a else SafeDiv_smallint := a div b;
end;
function SafeMod_smallint(a, b: smallint): smallint;
begin
  if (b = 0) or (b = -1) then SafeMod_smallint := a else SafeMod_smallint := a mod b;
end;
function SafeDiv_word(a, b: word): word;
begin
  if (b = 0) then SafeDiv_word := a else SafeDiv_word := a div b;
end;
function SafeMod_word(a, b: word): word;
begin
  if (b = 0) then SafeMod_word := a else SafeMod_word := a mod b;
end;
function SafeDiv_longint(a, b: longint): longint;
begin
  if (b = 0) or (b = -1) then SafeDiv_longint := a else SafeDiv_longint := a div b;
end;
function SafeMod_longint(a, b: longint): longint;
begin
  if (b = 0) or (b = -1) then SafeMod_longint := a else SafeMod_longint := a mod b;
end;
function SafeDiv_longword(a, b: longword): longword;
begin
  if (b = 0) then SafeDiv_longword := a else SafeDiv_longword := a div b;
end;
function SafeMod_longword(a, b: longword): longword;
begin
  if (b = 0) then SafeMod_longword := a else SafeMod_longword := a mod b;
end;
function SafeDiv_int64(a, b: int64): int64;
begin
  if (b = 0) or (b = -1) then SafeDiv_int64 := a else SafeDiv_int64 := a div b;
end;
function SafeMod_int64(a, b: int64): int64;
begin
  if (b = 0) or (b = -1) then SafeMod_int64 := a else SafeMod_int64 := a mod b;
end;
function SafeDiv_qword(a, b: qword): qword;
begin
  if (b = 0) then SafeDiv_qword := a else SafeDiv_qword := a div b;
end;
function SafeMod_qword(a, b: qword): qword;
begin
  if (b = 0) then SafeMod_qword := a else SafeMod_qword := a mod b;
end;

function f2(p0: longint; p1: qword): longint;
var
  v0: shortint;
  v1: byte;
  v2: smallint;
  v3: word;
  v4: longint;
  v5: longword;
  v6: int64;
  v7: qword;
  f2_li0: longint;
  f2_li1: longint;
  f2_li2: longint;
begin
  v0 := (-10);
  v1 := 255;
  v2 := (-903);
  v3 := 603;
  v4 := 866;
  v5 := 1;
  v6 := 434;
  v7 := 0;
  Mix(int64(p0));
  f2 := longint(p0 xor longint(v4 or v4));
end;

function f1(p0: longword; p1: byte): shortint;
var
  v0: shortint;
  v1: byte;
  v2: smallint;
  v3: word;
  v4: longint;
  v5: longword;
  v6: int64;
  v7: qword;
  f1_li0: longint;
  f1_li1: longint;
  f1_li2: longint;
begin
  v0 := (-127);
  v1 := 1;
  v2 := (-883);
  v3 := 21;
  v4 := (-812);
  v5 := 163;
  v6 := 606;
  v7 := 957;
  if true then
  begin
    Mix(int64(v0));
    for f1_li0 := 0 to 1 do
    begin
      v7 := qword(qword(SafeMod_qword(qword(v7), qword(v7)) xor v7) - SafeDiv_qword(qword(v7), qword(qword(v5))));
      v7 := qword(not v7);
    end;
    v4 := 4;
    for f1_li0 := 0 to v4 do
    begin
      v3 := v3;
      v4 := v4 - 1;
    end;
  end;
  f1 := shortint(shortint(-v0) * v0);
end;

function f0(p0: shortint; p1: shortint; p2: byte): longword;
var
  v0: shortint;
  v1: byte;
  v2: smallint;
  v3: word;
  v4: longint;
  v5: longword;
  v6: int64;
  v7: qword;
  f0_li0: longint;
  f0_li1: longint;
  f0_li2: longint;
begin
  v0 := 48;
  v1 := 140;
  v2 := (-32767);
  v3 := 861;
  v4 := 925;
  v5 := 151;
  v6 := (-60);
  v7 := 241;
  case longint(longint(v4 - SafeMod_longint(longint(v4), longint(v4)))) and 3 of
    0: begin
      if true then
      begin
        v4 := longint(longint(SafeDiv_longint(longint(v4), longint(v4)) + SafeDiv_longint(longint(v4), longint(v4))) + SafeDiv_longint(longint(v4), longint(v4)));
        v0 := shortint(byte(p1) shr (shortint(v0) and 7));
      end;
    end;
    1: begin
      v0 := shortint(v0);
      v5 := v5;
      v2 := smallint(-smallint(SafeDiv_smallint(smallint(v2), smallint(v2)) and smallint(v2 or v2)));
    end;
  else
    case longint(v4) and 3 of
      0: begin
        v4 := longint(-v4);
        v7 := v7;
        v5 := v5;
      end;
      1: begin
        v3 := v3;
        v4 := SafeMod_longint(longint(v4), longint(longint(longint(v4 - v4) xor f2(v4, v7))));
      end;
      2: begin
        v0 := v0;
      end;
    else
      v2 := v2;
      v1 := SafeDiv_byte(byte(byte(not v1)), byte(byte(byte(p2 and v1) + byte(v7))));
    end;
  end;
  v5 := longword(not longword(longword(v5 - v5) and longword(v5 and v5)));
  for f0_li0 := 2 to 2 do
  begin
    v4 := 2;
    for f0_li1 := 0 to v4 do
    begin
      v6 := int64(not v6);
      v7 := v7;
      v6 := v6;
      v4 := v4 - 1;
    end;
    for f0_li1 := 1 to 5 do
    begin
      v7 := qword(v7 * v7);
      v4 := v4;
    end;
  end;
  f0 := longword(byte(p2 xor v1));
end;

begin
  cs := 0;
  g0 := 0;
  g1 := 218;
  g2 := 291;
  g3 := 0;
  g4 := 0;
  g5 := 101;
  g6 := 9223372036854775806;
  g7 := 278;
  g8 := false;
  g9 := chr(73);
  g10 := true;
  g11 := false;
  g12 := chr(66);
  g13 := 613;
  g14 := 853;
  g15 := true;
  g16 := 633;
  g17 := chr(60);

  g5 := f0(shortint(shortint(g0 * g0) * shortint(g0 * g0)), g0, byte(not g1));
  if (g3 <> SafeDiv_word(word(g3), word(g14))) then
  begin
    g1 := byte(qword(longword(g1)));
    g3 := word(g14 - word(word(not g3) - SafeMod_word(word(g14), word(g3))));
  end;
  g3 := word(word(SafeMod_word(word(g14), word(g14)) xor g14) + word(g5));
  for li0 := 0 to 4 do
  begin
    g7 := g7;
  end;
  g4 := 4;
  for li0 := 0 to g4 do
  begin
    g7 := g7;
    g4 := g4 - 1;
  end;
  g9 := chr(longint(longint(longword(longint(-g4)) shr (longint(longint(g5)) and 31))) and 127);
  Mix(int64(g6));
  g4 := longint(g14);
  g12 := g9;
  Mix(int64(g4));
  g1 := g1;
  if g10 then
  begin
    g16 := SafeDiv_longword(longword(g13), longword(f0(g0, f1(g13, g1), g1)));
  end
  else
  begin
    g14 := word(word(word(g14 * g3) and word(g14 - g3)) - word(word(g3 or g3) and word(word(g14) shl (word(g3) and 15))));
    g15 := (longword(longword(longword(g5) shr (longword(g13) and 31)) xor longword(not g13)) < longword(not g16));
  end;

  { fold ALL live state into one number: the sole output }
  Mix(int64(g0));
  Mix(int64(g1));
  Mix(int64(g2));
  Mix(int64(g3));
  Mix(int64(g4));
  Mix(int64(g5));
  Mix(int64(g6));
  Mix(int64(g7));
  Mix(ord(g8));
  Mix(ord(g9));
  Mix(ord(g10));
  Mix(ord(g11));
  Mix(ord(g12));
  Mix(int64(g13));
  Mix(int64(g14));
  Mix(ord(g15));
  Mix(int64(g16));
  Mix(ord(g17));
  writeln(cs);
end.
