#!/bin/sh
# Phase 5 exception-design prototype — differential check.
#
#   native pxx build of exc_proto.pas   ==   hand-compiled exc_proto.wat
#
# The wasm side is generated by gen_exc_wat.py under the pending-flag +
# br_table scheme described in ../../../devdocs/dev/wasm/phase5-exceptions.md.
# Nothing here touches the compiler: this validates the DESIGN, before
# ir_codegen_wasm32.inc exists to get it wrong.
#
# Needs: a built compiler/pascal26, wat2wasm + wasm-validate + wasm2wat, node.
set -e
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../../.." && pwd)
work=${TMPDIR:-/tmp}/pxx-wasm-proto.$$
mkdir -p "$work"
trap 'rm -rf "$work"' EXIT

"$root/compiler/pascal26" "$here/exc_proto.pas" "$work/native" >/dev/null
"$work/native" > "$work/native.txt"

python3 "$here/gen_exc_wat.py" > "$work/exc.wat"
wat2wasm "$work/exc.wat" -o "$work/exc.wasm"
wasm-validate "$work/exc.wasm"
wasm2wat "$work/exc.wasm" -o "$work/exc.rt.wat"
node "$here/run.js" "$work/exc.wasm" > "$work/wasm.txt"

if diff -u "$work/native.txt" "$work/wasm.txt"; then
  echo "ok  wasm trace identical to native ($(wc -l < "$work/native.txt") lines)"
else
  echo "FAIL wasm trace diverges from native"
  exit 1
fi

# A POSITIVE sentinel, last line, reachable only after every check above
# passed: `set -e` kills the script before here on any failure. check_all.sh
# asserts this line is PRESENT rather than asserting nothing went wrong —
# "green is the absence of output" is indistinguishable from a script that died
# at line 1, which is how this suite stayed red across a handoff.
echo "PASS check"
