#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
#
# Emit the C shim that test-emit-obj links its cross-target objects against.
#
# WHY IT IS GENERATED RATHER THAN TYPED. The link step exists to prove an emitted
# .o is CONSUMABLE -- that its relocations resolve and a real linker will take
# it -- not to prove anything about what the RTL imports. But test_emit_obj.pas
# reaches the PAL socket/timer backend, so the object imports lwip_*,
# esp_timer_get_time and vTaskDelay, and a hand-written shim went stale the
# moment the PAL grew: 25 undefined references, from the PINNED compiler and
# from HEAD alike, on both xtensa ABIs. A hand-listed set of stubs would go
# stale again on the next PAL addition, and the diff that re-reds the row would
# look like it had nothing to do with PAL.
# bug-a-the-emit-obj-xtensa-link-shim-does-not-provide-the-pal-backends-esp-idf-symbols
#
# So the list comes from the OBJECT, every time. Whatever it leaves undefined
# gets an empty definition, except the four names the shim owns deliberately.
#
# ext_aliased_link IS ONE OF THOSE FOUR AND IS NOT A DETAIL. The readelf
# assertions in the recipe demand the object leave it UND -- that is the whole
# subject of bug-a-emit-obj-ignores-external-name-and-emits-the-pascal-identifier
# -- so it is defined here explicitly, by name, and never through the generated
# list. Letting the generator pick it up would still link, and would make this
# script the reason the row passes rather than the compiler.
#
# WHAT THIS ROW CAN AND CANNOT FAIL ON, stated because the change narrows it.
# It can no longer fail on a MISSING IMPORT: everything the object asks for is
# answered. It still fails on anything about the relocations themselves -- an
# out-of-range or malformed R_XTENSA_*/R_RISCV_*, a bad section reference, a
# symbol table the linker rejects -- which is what the step was written for. The
# caller MUST assert on `und seen`, NOT on `stubs generated`: a target can
# legitimately need zero stubs (riscv32's object imports only ext_notify and
# ext_aliased_link, which this shim owns), so a zero stub count is a real
# answer and cannot double as "the object was never read". `und seen: 0` is the
# one that means the UND list did not arrive -- a wrong path, a readelf whose
# columns moved -- and it would leave the old failure looking like a pass.
#
# Stubs are `void f(void) {}` regardless of the real signature. Nothing is
# called across this boundary at link time and no header is included, so there
# is nothing to disagree with. Data symbols get a function definition too: the
# link needs an address, not a type.
#
# Usage: tools/emit_obj_stub_shim.sh <obj> [<obj>...] > shim.c
set -u

if [ "$#" -lt 1 ]; then
  echo "usage: $0 <object> [<object>...]" >&2
  exit 2
fi

# The names this shim owns. ext_notify and ext_aliased_link are the test's own
# subject; main is the entry the link is given with -Wl,-e,main; app_main comes
# from the object under test and must never be stubbed away.
OWNED='ext_notify ext_aliased_link main app_main'

undefined() {
  for o in "$@"; do
    readelf -sW "$o" 2>/dev/null | awk '$7 == "UND" && $8 != "" { print $8 }'
  done | sed 's/@.*//' | sort -u
}

cat <<'HEADER'
/* GENERATED by tools/emit_obj_stub_shim.sh -- do not edit, and do not check in.
   The stub list below is read out of the object under test, so it tracks what
   the RTL and PAL actually import instead of what someone typed once. */
int captured;
void ext_notify(int v) { captured = v; }
void ext_aliased_link(int v) { (void)v; }
extern void app_main(void);
HEADER

n=0
seen=0
for sym in $(undefined "$@"); do
  seen=$((seen + 1))
  skip=0
  for owned in $OWNED; do
    [ "$sym" = "$owned" ] && skip=1
  done
  [ "$skip" = 1 ] && continue
  # A symbol name a C compiler cannot spell is not something this shim can
  # answer for; report it rather than emitting a file that will not build.
  case "$sym" in
    [A-Za-z_]*) ;;
    *) echo "$0: cannot stub a symbol that is not a C identifier: $sym" >&2; exit 1 ;;
  esac
  printf 'void %s(void) {}\n' "$sym"
  n=$((n + 1))
done

cat <<'FOOTER'
int main(void) { app_main(); return captured; }
FOOTER

echo "/* und seen: $seen, stubs generated: $n */"
