#!/usr/bin/env bash
# Generate SYMBOLS.md — a concise "helicopter view" of the compiler source so an
# agent can navigate by reading one file instead of repeatedly grepping the big
# .inc files. v1: routine signatures (function/procedure) grouped by file, via
# universal-ctags. Constants/types are NOT yet included (ctags' Pascal parser
# only tags routines; a section-state line-scan for const/type blocks is the
# planned v2). Re-run with `make symbols`.
#
# Deps: universal-ctags (JSON output + --langmap), jq.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=SYMBOLS.md
SRC=(compiler/*.inc compiler/*.pas)

if ! ctags --version 2>/dev/null | grep -qi 'Universal Ctags'; then
  echo "gen-symbols: universal-ctags required (found legacy/none)" >&2
  exit 1
fi

{
  echo "# PXX Symbol Index (routines)"
  echo
  echo "_Generated by \`make symbols\` (universal-ctags). Stamp: $(date -u +%Y-%m-%dT%H:%MZ),"
  echo "$(cat "${SRC[@]}" | wc -l) source lines._"
  echo
  echo "Locating aid only — **verify the line before editing**; line numbers drift"
  echo "between regens. The \`.inc\` files are \`{\$include}\`d into one unit, so"
  echo "symbols share a single flat namespace (a name has one definition project-wide)."
  echo "Forward declarations and their implementations both appear (two lines)."
  echo "Constants/types are not indexed yet (see tools/gen-symbols.sh header)."
  echo
  ctags --languages=Pascal --langmap=Pascal:+.inc --output-format=json \
        --fields=+n -f - "${SRC[@]}" 2>/dev/null \
  | jq -r '"\(.path)\t\(.line)\t\(.pattern)"' \
  | sort -t$'\t' -k1,1 -k2,2n \
  | awk -F'\t' '
      {
        path=$1; line=$2; pat=$3;
        sub(/^\/\^/, "", pat); sub(/\$\/$/, "", pat);   # strip ctags /^...$/
        gsub(/[ \t]+$/, "", pat);                       # trailing ws
        if (path != prev) { printf "\n## %s\n\n", path; prev=path }
        printf "- `%s`  :%s\n", pat, line
      }'
} > "$OUT"

echo "wrote $OUT ($(grep -c '^- ' "$OUT") routines)"
