#!/usr/bin/env python3
"""Generate compiler/crtl_names.inc — the crtl function -> header map.

WHY IT IS GENERATED. `CCrtlHeaderForName` in compiler/cparser.inc used to be a
hand-written if-chain of 87 names across 5 headers. crtl actually publishes 300+
functions across 20+ modules, so the list was a 24% sample of B's data, authored
in A's file, with no way to notice drift. It is consulted when a C89-style
program declares a libc function by hand instead of including its header: a name
the list does not know is never pulled from crtl, so it becomes a glibc import in
a build that is supposed to be libc-free. `imaxdiv` being absent is a piece of
why bug-c-crtl-auto-pull-depends-on-the-pascal-preludes-unit-count stayed hidden.

Generating it inverts the direction: lib/crtl is the source of truth and the
compiler stops remembering B's contents. Run --check in lib-test so a new crtl
function that forgets to regenerate fails there rather than silently.

SHAPE OF THE OUTPUT, and why. Names are bucketed by first letter into one string
per letter, `name:header` space-delimited. That is not decoration: this map is
consulted for EVERY `identifier(` in the token stream (the implicit-call scan),
which for sqlite's amalgamation is ~1M probes. A single flat 8 KB string would
make that scan quadratic-ish in practice; per-letter buckets keep each probe to
~13 entries, which is fewer comparisons than the 87-entry if-chain it replaces.

EXCLUSIONS are deliberate, not omissions:
  - `pthread.h` — pulling it without --threadsafe is a hard error by design
    (RegisterExternal refuses `__pxx_p*`). Auto-pulling it from a hand
    prototype would turn a working program into a compile error.
  - `__`-prefixed names — internal kernels, never a user's libc call.
  - names crtl declares but does not define — PAL entry points and genuinely
    system-provided symbols; pulling their header would not supply them.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INC = os.path.join(ROOT, "lib", "crtl", "include")
SRC = os.path.join(ROOT, "lib", "crtl", "src")
OUT = os.path.join(ROOT, "compiler", "crtl_names.inc")

EXCLUDED_HEADERS = {"pthread.h"}

sys.path.insert(0, os.path.join(ROOT, "tools"))
from crtl_reachability import scan, strip_noise  # one scanner, no drift


def read(p):
    with open(p, errors="replace") as f:
        return f.read()


def build():
    defined = {}
    for dirpath, _, names in os.walk(SRC):
        for nm in names:
            if not nm.endswith(".c"):
                continue
            p = os.path.join(dirpath, nm)
            rel = os.path.relpath(p, SRC)
            for fn in scan(read(p), want_definition=True):
                defined.setdefault(fn, set()).add(rel)

    # name -> header. When two headers declare it (strings.h/string.h,
    # wctype.h/wchar.h), prefer the one whose own sibling .c defines it —
    # that is the header the auto-pull can satisfy in one step.
    chosen = {}
    for dirpath, _, names in os.walk(INC):
        for nm in names:
            if not nm.endswith(".h"):
                continue
            p = os.path.join(dirpath, nm)
            rel = os.path.relpath(p, INC).replace(os.sep, "/")
            if rel in EXCLUDED_HEADERS:
                continue
            sib = rel[:-2] + ".c"
            for fn in scan(read(p), want_definition=False):
                if fn.startswith("__") or fn not in defined:
                    continue
                prev = chosen.get(fn)
                if prev is None:
                    chosen[fn] = rel
                elif sib in defined[fn] and prev[:-2] + ".c" not in defined[fn]:
                    chosen[fn] = rel
                elif rel < prev and (sib in defined[fn]) == (prev[:-2] + ".c" in defined[fn]):
                    chosen[fn] = rel

    buckets = {}
    for fn, hdr in sorted(chosen.items()):
        buckets.setdefault(fn[0].lower(), []).append("%s:%s" % (fn, hdr))
    return chosen, buckets


def render(chosen, buckets):
    L = []
    L.append("{ GENERATED by tools/gen_crtl_map.py -- DO NOT EDIT.")
    L.append("")
    L.append("  The crtl function -> header map, read out of lib/crtl rather than")
    L.append("  remembered here. Consulted when a C program declares (or calls) a libc")
    L.append("  function without including its header: the header is then synthesised so")
    L.append("  the normal auto-pull supplies a crtl body instead of a glibc import.")
    L.append("")
    L.append("  Bucketed by first letter because the implicit-call scan probes this for")
    L.append("  every `identifier(` in the token stream. Regenerate after adding a crtl")
    L.append("  function; `python3 tools/gen_crtl_map.py --check` fails when stale.")
    L.append("")
    L.append("  %d functions across %d headers. }" % (len(chosen), len(set(chosen.values()))))
    L.append("")
    L.append("function CrtlNameBucket(c: Char): AnsiString;")
    L.append("begin")
    L.append("  case c of")
    for letter in sorted(buckets):
        body = " " + " ".join(buckets[letter]) + " "
        # Pascal string literals: chunk so no source line runs absurdly long.
        parts, cur = [], ""
        for tok in body.strip().split(" "):
            if len(cur) + len(tok) + 1 > 88:
                parts.append(cur)
                cur = tok
            else:
                cur = (cur + " " + tok) if cur else tok
        parts.append(cur)
        lit = " +\n      ".join("'%s'" % (" " + p + " ") for p in parts)
        L.append("    '%s': Result :=\n      %s;" % (letter, lit))
    L.append("  else Result := '';")
    L.append("  end;")
    L.append("end;")
    L.append("")
    L.append("{ Bit L set = this bucket holds a name of length L (1..30). The implicit-call")
    L.append("  sweep tests this BEFORE scanning the bucket, which rejects almost every")
    L.append("  identifier in real C source in one AND: crtl's names are short and a")
    L.append("  codebase's own are not (sqlite3VdbeMemGrow is 18 characters and no bucket")
    L.append("  has an 18). Without it the sweep cost +25% on sqlite's amalgamation, since")
    L.append("  it can no longer stop early the way five fixed headers allowed. }")
    L.append("function CrtlNameLenMask(c: Char): Integer;")
    L.append("begin")
    L.append("  case c of")
    for letter in sorted(buckets):
        mask = 0
        for e in buckets[letter]:
            ln = len(e.split(":")[0])
            if 1 <= ln <= 30:
                mask |= 1 << ln
        L.append("    '%s': Result := %d;" % (letter, mask))
    L.append("  else Result := 0;")
    L.append("  end;")
    L.append("end;")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    chosen, buckets = build()
    text = render(chosen, buckets)
    if "--check" in sys.argv:
        old = read(OUT) if os.path.exists(OUT) else ""
        if old != text:
            print("crtl-map: compiler/crtl_names.inc is STALE — "
                  "run: python3 tools/gen_crtl_map.py", file=sys.stderr)
            return 1
        print("crtl-map: OK -- %d crtl functions mapped to %d headers"
              % (len(chosen), len(set(chosen.values()))))
        return 0
    with open(OUT, "w") as f:
        f.write(text)
    print("crtl-map: wrote %s (%d functions, %d headers)"
          % (os.path.relpath(OUT, ROOT), len(chosen), len(set(chosen.values()))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
