#!/usr/bin/env bash
#
# install.sh — drop a `pxx` wrapper on your PATH that runs the pinned PXX
# compiler with this checkout's library roots already on the unit search path.
#
# The wrapper points at stable_linux_amd64/default/pinned (a symlink), so a
# later `make pin` is picked up automatically — no reinstall needed. It scans
# lib/ for directories that actually contain units (.pas/.pp/.h) and passes each
# as a -Fu root, so `pxx foo.pas` resolves rtl/pcl units (and C-header bindings
# like gtk3_c.h) from any working directory, with no flags.
#
# Usage:
#   tools/install.sh                 # install to ~/.local/bin
#   tools/install.sh --bindir DIR    # install to DIR
#   tools/install.sh --uninstall     # remove the wrapper
#
# After install, ensure the bindir is on your PATH (the script tells you).

set -euo pipefail

# Repo root = parent of this script's dir, made absolute.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

BINDIR="${HOME}/.local/bin"
ACTION="install"
COMPILER_OVERRIDE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --bindir) BINDIR="$2"; shift 2 ;;
    --compiler) COMPILER_OVERRIDE="$2"; shift 2 ;;   # use this binary instead of the pinned symlink (e.g. a native make-bootstrap build)
    --uninstall) ACTION="uninstall"; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

WRAPPER="${BINDIR}/pxx"

if [ "$ACTION" = "uninstall" ]; then
  if [ -e "$WRAPPER" ]; then rm -f "$WRAPPER"; echo "removed $WRAPPER"; else echo "no wrapper at $WRAPPER"; fi
  exit 0
fi

if [ -n "$COMPILER_OVERRIDE" ]; then
  PINNED="$COMPILER_OVERRIDE"
else
  PINNED="${ROOT}/stable_linux_amd64/default/pinned"
fi
if [ ! -e "$PINNED" ]; then
  echo "no compiler at $PINNED" >&2
  echo "run 'make stabilize && make pin' first (or pass --compiler PATH)." >&2
  exit 1
fi

# Discover lib roots: every dir under lib/ that holds at least one unit source.
# Excludes:
#   */historic    — superseded sources kept for reference only
#   */platform/*  except posix — target-selected PAL backends; the posix one is
#                 the host default, and including e.g. platform/esp as a peer
#                 root would shadow posix units of the same name (platform_*).
# (The folder layout is due a review before a release — see the install help.)
mapfile -t LIBDIRS < <(
  find "$ROOT/lib" -type f \( -name '*.pas' -o -name '*.pp' -o -name '*.h' \) -printf '%h\n' \
    | sort -u \
    | grep -vE '/historic(/|$)' \
    | { grep -vE '/platform/' || true; } \
  ; printf '%s/lib/rtl/platform/posix\n' "$ROOT"   # re-add the host PAL backend
)
# Dedup (the posix re-add may duplicate) and keep only existing dirs.
mapfile -t LIBDIRS < <(printf '%s\n' "${LIBDIRS[@]}" | sort -u)

mkdir -p "$BINDIR"

{
  echo '#!/bin/sh'
  echo '# Generated by tools/install.sh — runs the pinned PXX compiler with this'
  echo '# checkout'"'"'s library roots on the unit search path. Re-run install.sh'
  echo '# to refresh the library list; the compiler symlink auto-tracks re-pins.'
  printf 'exec "%s" \\\n' "$PINNED"
  for d in "${LIBDIRS[@]}"; do
    printf '  -Fu"%s" \\\n' "$d"
  done
  echo '  "$@"'
} > "$WRAPPER"
chmod +x "$WRAPPER"

echo "installed: $WRAPPER"
echo "  -> $PINNED"
echo "  unit roots (${#LIBDIRS[@]}):"
for d in "${LIBDIRS[@]}"; do echo "       $d"; done

case ":$PATH:" in
  *":$BINDIR:"*) ;;
  *) echo
     echo "NOTE: $BINDIR is not on your PATH. Add it, e.g.:"
     echo "      echo 'export PATH=\"$BINDIR:\$PATH\"' >> ~/.bashrc && source ~/.bashrc" ;;
esac

echo
echo "try:  pxx ${ROOT}/examples/life/life.pas /tmp/life && /tmp/life"
