#!/usr/bin/env sh
# SPDX-License-Identifier: MPL-2.0
# fgl corpus runner -- rung 2 of the Pascal real-world ladder.
#
# Compiles REAL FPC 3.2.2 `fgl.pp` (the reference RTL's generic-container unit,
# fetched by tools/install_lib_candidates.sh fpc-rtl) with pxx --mimic-fpc, and
# runs the drivers in test/fgl/ against it. Each driver's stdout must byte-match
# its .expected -- and those .expected files were generated by compiling the SAME
# drivers against the SAME fgl.pp with FPC 3.2.2 itself, so the assertion is
# behavioural parity with the reference compiler on real library code, NOT any
# claim about the emitted machine code.
#
# Skips are EXPLICIT: test/fgl/pxx.skip lists one driver per line as
# "name.pas<TAB>reason"; anything not passing and not listed = FAIL. Same
# discipline as test/c-conformance/pxx.skip -- remove the line when the ticket
# it names is fixed and the runner then enforces the pass.
#
# Usage: tools/run_fgl_corpus.sh [compiler] [objpas-dir]
#   compiler    default compiler/pascal26
#   objpas-dir  default library_candidates/fpc-rtl/rtl/objpas
set -u

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
CC="$ROOT/compiler/pascal26"
OBJPAS="$ROOT/library_candidates/fpc-rtl/rtl/objpas"
case "${1:-}" in ''|--*) ;; *) CC="$1"; shift ;; esac
case "${1:-}" in ''|--*) ;; *) OBJPAS="$1"; shift ;; esac
while [ $# -gt 0 ]; do
  case "$1" in
    *) echo "run_fgl_corpus: unknown option $1" >&2; exit 2 ;;
  esac
done

LABEL="test-fgl"
DRIVERS="$ROOT/test/fgl"
SKIPLIST="$DRIVERS/pxx.skip"
WORK="${TMPDIR:-/tmp}/pxx_fgl_corpus.$$"
TIMEOUT_S="$(awk -v s="${TESTMGR_TIME_SCALE:-1}" -v l="${TESTMGR_LOAD_SCALE:-1}" \
  'BEGIN { t=20*s*l; printf "%d", (t<20 ? 20 : t) }')"

# A pre-3.2.2-era system tree is the historic fallback: the check used to live
# inline in `make test-core` guarded on this path, and printed a silent SKIP on
# every box that did not have it.
if [ ! -f "$OBJPAS/fgl.pp" ] && [ -f /usr/share/fpcsrc/3.2.2/rtl/objpas/fgl.pp ]; then
  OBJPAS=/usr/share/fpcsrc/3.2.2/rtl/objpas
fi
if [ ! -f "$OBJPAS/fgl.pp" ]; then
  echo "$LABEL: SKIP -- no fgl.pp at $OBJPAS (run tools/install_lib_candidates.sh fpc-rtl)"
  exit 0
fi

mkdir -p "$WORK"
trap 'rm -rf "$WORK"' EXIT INT TERM

pass=0; fail=0; skip=0; failed=""

for src in "$DRIVERS"/*.pas; do
  [ -f "$src" ] || continue
  name="$(basename "$src")"
  exp="${src%.pas}.expected"

  reason=""
  if [ -f "$SKIPLIST" ]; then
    reason="$(awk -v n="$name" '$1==n { $1=""; sub(/^[ \t]+/,""); print; exit }' "$SKIPLIST")"
  fi
  if [ -n "$reason" ]; then
    skip=$((skip+1))
    echo "SKIP $name -- $reason"
    continue
  fi

  if [ ! -f "$exp" ]; then
    fail=$((fail+1)); failed="$failed $name(no-expected)"
    echo "FAIL $name -- no $(basename "$exp") beside the driver"
    continue
  fi

  bin="$WORK/${name%.pas}"
  if ! "$CC" --mimic-fpc -Fu"$OBJPAS" "$src" "$bin" > "$WORK/cc.log" 2>&1; then
    fail=$((fail+1)); failed="$failed $name(compile)"
    echo "FAIL $name -- compile error:"
    sed -n '1,4p' "$WORK/cc.log" | sed 's/^/    /'
    continue
  fi

  timeout "$TIMEOUT_S" "$bin" > "$WORK/out.txt" 2>&1
  rc=$?
  if [ "$rc" != "0" ]; then
    fail=$((fail+1)); failed="$failed $name(exit=$rc)"
    echo "FAIL $name -- exit code $rc (want 0)"
    sed -n '1,4p' "$WORK/out.txt" | sed 's/^/    /'
    continue
  fi
  if ! cmp -s "$WORK/out.txt" "$exp"; then
    fail=$((fail+1)); failed="$failed $name(output)"
    echo "FAIL $name -- output differs from the FPC 3.2.2 oracle:"
    diff -u "$exp" "$WORK/out.txt" | sed -n '1,10p' | sed 's/^/    /'
    continue
  fi
  pass=$((pass+1))
  echo "PASS $name"
done

echo "$LABEL: $pass pass, $fail fail, $skip skip (of $((pass+fail+skip)))"
if [ "$fail" != "0" ]; then
  echo "$LABEL: FAILURES:$failed"
  exit 1
fi
echo "$LABEL: PASS -- real FPC 3.2.2 fgl.pp, $pass driver(s) match the FPC oracle"
